#!/bin/bash

echo "🚀 HiveMind Deployment Script"
echo "=============================="

echo "📋 Prerequisites:"
echo "- MongoDB Atlas account and connection string"
echo "- Gmail account with App Password enabled"
echo "- OpenAI API key (optional)"
echo ""

echo "🔑 Generated JWT Secret: DMnFu7pOUKhkxnPX8Gqr0loZKGq5+YtGTcBXUmnzhxY="
echo ""

echo "📝 Manual Steps Required:"
echo ""
echo "1. DEPLOY BACKEND TO RENDER:"
echo "   • Go to: https://render.com"
echo "   • New Web Service -> Connect GitHub -> Select HiveMind repo"
echo "   • Settings:"
echo "     - Name: hivemind-backend"
echo "     - Environment: Node"
echo "     - Root Directory: BackEnd"
echo "     - Build Command: npm install"
echo "     - Start Command: node server.js"
echo "   • Environment Variables (copy these exactly):"
echo "     NODE_ENV=production"
echo "     PORT=10000"
echo "     MONGO_URI=mongodb+srv://username:password@cluster.mongodb.net/hivemind"
echo "     JWT_SECRET=DMnFu7pOUKhkxnPX8Gqr0loZKGq5+YtGTcBXUmnzhxY="
echo "     FRONTEND_URL=https://hive-mind-ai.vercel.app"
echo "     GMAIL_USER=your-email@gmail.com"
echo "     GMAIL_APP_PASSWORD=your-app-password"
echo "     OPENAI_API_KEY=sk-your-openai-key"
echo ""

echo "2. DEPLOY FRONTEND TO VERCEL:"
echo "   • Go to: https://vercel.com"
echo "   • New Project -> Import HiveMind repo"
echo "   • Settings:"
echo "     - Framework: Other"
echo "     - Root Directory: /"
echo "     - Build Command: echo 'Static site'"
echo "     - Output Directory: FrontEnd"
echo "     - Install Command: echo 'No install needed'"
echo ""

echo "3. GET REQUIRED CREDENTIALS:"
echo ""
echo "   MongoDB Atlas:"
echo "   • https://mongodb.com/atlas"
echo "   • Create free cluster"
echo "   • Create user and get connection string"
echo ""
echo "   Gmail App Password:"
echo "   • Enable 2FA on Gmail"
echo "   • https://myaccount.google.com/apppasswords"
echo "   • Generate 'Mail' app password"
echo ""
echo "   OpenAI API Key:"
echo "   • https://platform.openai.com"
echo "   • Create account, get API key"
echo ""

echo "4. AFTER DEPLOYMENT:"
echo "   • Update FrontEnd/config.js with your Render backend URL"
echo "   • Test both services"
echo "   • Verify email OTP functionality"
echo ""

echo "🎯 Quick Setup Links:"
echo "• Render: https://render.com"
echo "• Vercel: https://vercel.com" 
echo "• MongoDB: https://mongodb.com/atlas"
echo "• Gmail Settings: https://myaccount.google.com/apppasswords"
echo "• OpenAI: https://platform.openai.com"
echo ""

echo "✅ All configuration files are ready!"
echo "📁 Check DEPLOYMENT_GUIDE.md for detailed instructions"